services:
  mysqldb:
    image: tiagosp13/mysql_api-asymmetric-encrypt
    container_name: mysql_api-asymmetric-encrypt
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: config
    ports:
      - "3308:3306"
    # volumes:
    #   - ./db/backup:/var/lib/mysql
    networks:
      - network
  api-asymmetric-encrypt:
    image: tiagosp13/api-asymmetric-encrypt
    container_name: api-asymmetric-encrypt
    entrypoint: ./entrypoint.sh
    restart: always
    build: ./
    working_dir: /api-asymmetric-encrypt
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
      ASYMMETRIC_ENCRYPT_PRIVATE_KEY: ${ASYMMETRIC_ENCRYPT_PRIVATE_KEY}
      ASYMMETRIC_ENCRYPT_PUBLIC_KEY: ${ASYMMETRIC_ENCRYPT_PUBLIC_KEY}
    volumes:
      - .:/api-asymmetric-encrypt
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - mysqldb
    depends_on:
      - mysqldb
    networks:
      - network
networks:
  network:
    driver: bridge
