server:
  port: 8080

security:
  rsa:
    private_key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAIbPH7WvaSdZpDiDuulvx7bhReaURxWxohZLzJPMkkDes9CxY3Zwh6a/a4oPyeD7dwvjTVCmg0t242SwMBMb1ZysEtu3CYY013YBH4PfUxsRPKddMu4BVFWwnLTlCgOg7KrHWHN0eegS/GSS0mk0mIsbgRbR6N6Qjr3VV2FbKkWpAgMBAAECgYEAgoBxzv0vC3Pg4QDM6XxXVre/Zla2dc7O/UyFj7KjBn9QjT+b7KVE/GwkG7PrF4v3k5+IUgHP6jb+LJPPBkCUyTs9V4HEj+CrcPRx4hOtvEtw65hTRsIpGr1v1/wwFH+T3D7LLmhtHd5VjmClqQ7wbJyqAcOw6lrRCMAcdw5ZEU0CQQDQxcP4YNKYvhBw+FQusTgYayVH4Z5sjLfXg/GuClyksukVFI9P1Cy3cuXSs4aBNIOzB6EBbqFQJ38yQsOv8VvrAkEApU4O5CpGU2KVS4MoGP9XDbMCtKkyBazCXiHZEqybVlYfzPzx5oQ9O+2k1UXH/3mYK/DvLgl7UytH0PuwtyEjuwJAboOBzYVTdc+G3IZX6a+eRi7RuU9RkZyb5NXPpZWOnRCoGaSciGGEmkeUKQkndlXaMXckX6G0er2ts2lsNULKqQJAP2Ib0Z7oEkcFqcujj1ow3f7atbz+gjCI4qEl48QtV8B0NxxyAIqKFDV984zrL+lG0Op0O3nFQNGimt43FzDsywJBAIdMZGYilxlnf4p3iKejZ4Vugp0eQMs9sfICKb8G+LgwTTVbHmHTyevfXg9NTG3uUxNNKIVnacIxYKyTmc+R4zU=
    public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCGzx+1r2knWaQ4g7rpb8e24UXmlEcVsaIWS8yTzJJA3rPQsWN2cIemv2uKD8ng+3cL401QpoNLduNksDATG9WcrBLbtwmGNNd2AR+D31MbETynXTLuAVRVsJy05QoDoOyqx1hzdHnoEvxkktJpNJiLG4EW0ejekI691VdhWypFqQIDAQAB

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/config?useSSL=false
    username: root
    password: admin

  jpa:
    hibernate.ddl-auto: none
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
